# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160421_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
